var tree = [["Eloquent",,"",
                [["Endec",,"",
                [["Encoding",,"",
                [["Base64","Eloquent\/Endec\/Encoding\/Base64.html","",
                [["Base64Decoder","Eloquent\/Endec\/Encoding\/Base64\/Base64Decoder.html"," < AbstractDataTransform",
                [        ]],["Base64Encoder","Eloquent\/Endec\/Encoding\/Base64\/Base64Encoder.html"," < AbstractDataTransform",
                [        ]]        ]],["Exception","Eloquent\/Endec\/Encoding\/Exception.html","",
                [["InvalidEncodedDataException","Eloquent\/Endec\/Encoding\/Exception\/InvalidEncodedDataException.html"," < Exception",
                [        ]]        ]],["Hex","Eloquent\/Endec\/Encoding\/Hex.html","",
                [["HexDecoder","Eloquent\/Endec\/Encoding\/Hex\/HexDecoder.html"," < AbstractDataTransform",
                [        ]],["HexEncoder","Eloquent\/Endec\/Encoding\/Hex\/HexEncoder.html"," < AbstractDataTransform",
                [        ]]        ]]        ]],["Transform","Eloquent\/Endec\/Transform.html","",
                [["Exception","Eloquent\/Endec\/Transform\/Exception.html","",
                [["TransformExceptionInterface","Eloquent\/Endec\/Transform\/Exception\/TransformExceptionInterface.html","",
                [        ]]        ]],["AbstractDataTransform","Eloquent\/Endec\/Transform\/AbstractDataTransform.html","",
                [        ]],["DataTransformInterface","Eloquent\/Endec\/Transform\/DataTransformInterface.html","",
                [        ]]        ]]        ]]        ]]        ]

