var tree = [["Eloquent",,"",
                [["Endec","Eloquent\/Endec.html","",
                [["Base16","Eloquent\/Endec\/Base16.html","",
                [["Base16","Eloquent\/Endec\/Base16\/Base16.html"," < AbstractCodec",
                [        ]],["Base16DecodeNativeStreamFilter","Eloquent\/Endec\/Base16\/Base16DecodeNativeStreamFilter.html"," < AbstractNativeStreamFilter",
                [        ]],["Base16DecodeTransform","Eloquent\/Endec\/Base16\/Base16DecodeTransform.html"," < AbstractDataTransform",
                [        ]],["Base16EncodeNativeStreamFilter","Eloquent\/Endec\/Base16\/Base16EncodeNativeStreamFilter.html"," < AbstractNativeStreamFilter",
                [        ]],["Base16EncodeTransform","Eloquent\/Endec\/Base16\/Base16EncodeTransform.html","",
                [        ]]        ]],["Base32","Eloquent\/Endec\/Base32.html","",
                [["Base32DecodeTransform","Eloquent\/Endec\/Base32\/Base32DecodeTransform.html"," < AbstractDataTransform",
                [        ]],["Base32EncodeTransform","Eloquent\/Endec\/Base32\/Base32EncodeTransform.html"," < AbstractDataTransform",
                [        ]]        ]],["Base64","Eloquent\/Endec\/Base64.html","",
                [["Base64","Eloquent\/Endec\/Base64\/Base64.html"," < AbstractCodec",
                [        ]],["Base64DecodeNativeStreamFilter","Eloquent\/Endec\/Base64\/Base64DecodeNativeStreamFilter.html"," < AbstractNativeStreamFilter",
                [        ]],["Base64DecodeTransform","Eloquent\/Endec\/Base64\/Base64DecodeTransform.html"," < AbstractDataTransform",
                [        ]],["Base64EncodeNativeStreamFilter","Eloquent\/Endec\/Base64\/Base64EncodeNativeStreamFilter.html"," < AbstractNativeStreamFilter",
                [        ]],["Base64EncodeTransform","Eloquent\/Endec\/Base64\/Base64EncodeTransform.html"," < AbstractDataTransform",
                [        ]]        ]],["Exception","Eloquent\/Endec\/Exception.html","",
                [["InvalidEncodedDataException","Eloquent\/Endec\/Exception\/InvalidEncodedDataException.html"," < Exception",
                [        ]]        ]],["Transform","Eloquent\/Endec\/Transform.html","",
                [["Exception","Eloquent\/Endec\/Transform\/Exception.html","",
                [["TransformExceptionInterface","Eloquent\/Endec\/Transform\/Exception\/TransformExceptionInterface.html","",
                [        ]]        ]],["AbstractDataTransform","Eloquent\/Endec\/Transform\/AbstractDataTransform.html","",
                [        ]],["AbstractNativeStreamFilter","Eloquent\/Endec\/Transform\/AbstractNativeStreamFilter.html"," < php_user_filter",
                [        ]],["DataTransformInterface","Eloquent\/Endec\/Transform\/DataTransformInterface.html","",
                [        ]],["TransformStream","Eloquent\/Endec\/Transform\/TransformStream.html","",
                [        ]],["TransformStreamInterface","Eloquent\/Endec\/Transform\/TransformStreamInterface.html","",
                [        ]]        ]],["AbstractCodec","Eloquent\/Endec\/AbstractCodec.html","",
                [        ]],["CodecInterface","Eloquent\/Endec\/CodecInterface.html","",
                [        ]],["DecoderInterface","Eloquent\/Endec\/DecoderInterface.html","",
                [        ]],["EncoderInterface","Eloquent\/Endec\/EncoderInterface.html","",
                [        ]],["Endec","Eloquent\/Endec\/Endec.html","",
                [        ]]        ]]        ]]        ]

