var tree = [["Eloquent",,"",
                [["Endec",,"",
                [["Encoding","Eloquent\/Endec\/Encoding.html","",
                [["Exception","Eloquent\/Endec\/Encoding\/Exception.html","",
                [["InvalidEncodedDataException","Eloquent\/Endec\/Encoding\/Exception\/InvalidEncodedDataException.html"," < Exception",
                [        ]]        ]],["Base64Decoder","Eloquent\/Endec\/Encoding\/Base64Decoder.html"," < AbstractDataTransform",
                [        ]],["Base64Encoder","Eloquent\/Endec\/Encoding\/Base64Encoder.html"," < AbstractDataTransform",
                [        ]],["HexDecoder","Eloquent\/Endec\/Encoding\/HexDecoder.html"," < AbstractDataTransform",
                [        ]],["HexEncoder","Eloquent\/Endec\/Encoding\/HexEncoder.html"," < AbstractDataTransform",
                [        ]]        ]],["Transform","Eloquent\/Endec\/Transform.html","",
                [["Exception","Eloquent\/Endec\/Transform\/Exception.html","",
                [["TransformExceptionInterface","Eloquent\/Endec\/Transform\/Exception\/TransformExceptionInterface.html","",
                [        ]]        ]],["AbstractDataTransform","Eloquent\/Endec\/Transform\/AbstractDataTransform.html","",
                [        ]],["DataTransformInterface","Eloquent\/Endec\/Transform\/DataTransformInterface.html","",
                [        ]]        ]]        ]]        ]]        ]

